spring:
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
api:
  zipcode:
    key: 01HXQHT3F253CD4BK48CF2C2Y9
    url: https://api.zipcodestack.com/v1/search